"""County-to-region mapping for Texas geographic data.

Maps Texas county names (title-cased, no "County" suffix, as in TIGER/Census data)
to one of the 8 zip_region values used in personas.json.
Counties absent from this dict are dropped (not assigned "Other").
"""

COUNTY_TO_REGION: dict[str, str] = {
    # Austin Metro
    "Travis": "Austin Metro",
    "Williamson": "Austin Metro",
    "Hays": "Austin Metro",
    "Bastrop": "Austin Metro",
    "Caldwell": "Austin Metro",
    # Houston Metro
    "Harris": "Houston Metro",
    "Fort Bend": "Houston Metro",
    "Montgomery": "Houston Metro",
    "Brazoria": "Houston Metro",
    "Galveston": "Houston Metro",
    "Liberty": "Houston Metro",
    "Waller": "Houston Metro",
    "Chambers": "Houston Metro",
    "Austin": "Houston Metro",  # Austin County (not the city)
    # Dallas-Fort Worth
    "Dallas": "Dallas-Fort Worth",
    "Tarrant": "Dallas-Fort Worth",
    "Collin": "Dallas-Fort Worth",
    "Denton": "Dallas-Fort Worth",
    "Ellis": "Dallas-Fort Worth",
    "Johnson": "Dallas-Fort Worth",
    "Kaufman": "Dallas-Fort Worth",
    "Parker": "Dallas-Fort Worth",
    "Rockwall": "Dallas-Fort Worth",
    "Hunt": "Dallas-Fort Worth",
    "Wise": "Dallas-Fort Worth",
    # San Antonio Metro
    "Bexar": "San Antonio Metro",
    "Comal": "San Antonio Metro",
    "Guadalupe": "San Antonio Metro",
    "Medina": "San Antonio Metro",
    "Wilson": "San Antonio Metro",
    "Atascosa": "San Antonio Metro",
    "Bandera": "San Antonio Metro",
    "Kendall": "San Antonio Metro",
    # Permian Basin
    "Midland": "Permian Basin",
    "Ector": "Permian Basin",
    "Martin": "Permian Basin",
    "Andrews": "Permian Basin",
    "Howard": "Permian Basin",
    "Reeves": "Permian Basin",
    "Ward": "Permian Basin",
    "Winkler": "Permian Basin",
    "Loving": "Permian Basin",
    "Crane": "Permian Basin",
    "Upton": "Permian Basin",
    "Reagan": "Permian Basin",
    "Glasscock": "Permian Basin",
    "Sterling": "Permian Basin",
    "Dawson": "Permian Basin",
    "Borden": "Permian Basin",
    "Scurry": "Permian Basin",
    "Mitchell": "Permian Basin",
    # Rio Grande Valley
    "Cameron": "Rio Grande Valley",
    "Hidalgo": "Rio Grande Valley",
    "Starr": "Rio Grande Valley",
    "Willacy": "Rio Grande Valley",
    "Webb": "Rio Grande Valley",
    "Zapata": "Rio Grande Valley",
    "Maverick": "Rio Grande Valley",
    "Jim Hogg": "Rio Grande Valley",
    # East Texas
    "Smith": "East Texas",
    "Gregg": "East Texas",
    "Harrison": "East Texas",
    "Rusk": "East Texas",
    "Henderson": "East Texas",
    "Anderson": "East Texas",
    "Cherokee": "East Texas",
    "Nacogdoches": "East Texas",
    "Angelina": "East Texas",
    "Tyler": "East Texas",
    "Polk": "East Texas",
    "San Jacinto": "East Texas",
    "Trinity": "East Texas",
    "Houston": "East Texas",  # Houston County (not the city)
    "Jasper": "East Texas",
    "Newton": "East Texas",
    "Shelby": "East Texas",
    "Sabine": "East Texas",
    "San Augustine": "East Texas",
    "Hardin": "East Texas",
    "Orange": "East Texas",
    "Jefferson": "East Texas",
    "Panola": "East Texas",
    "Marion": "East Texas",
    "Upshur": "East Texas",
    "Camp": "East Texas",
    "Wood": "East Texas",
    "Franklin": "East Texas",
    "Titus": "East Texas",
    # Panhandle
    "Potter": "Panhandle",
    "Randall": "Panhandle",
    "Hutchinson": "Panhandle",
    "Gray": "Panhandle",
    "Moore": "Panhandle",
    "Hansford": "Panhandle",
    "Ochiltree": "Panhandle",
    "Lipscomb": "Panhandle",
    "Sherman": "Panhandle",
    "Hartley": "Panhandle",
    "Dallam": "Panhandle",
    "Armstrong": "Panhandle",
    "Carson": "Panhandle",
    "Donley": "Panhandle",
    "Wheeler": "Panhandle",
    "Roberts": "Panhandle",
    "Hemphill": "Panhandle",
    "Oldham": "Panhandle",
    "Deaf Smith": "Panhandle",
    "Parmer": "Panhandle",
    "Castro": "Panhandle",
    "Swisher": "Panhandle",
    "Briscoe": "Panhandle",
    "Hall": "Panhandle",
    "Childress": "Panhandle",
    "Collingsworth": "Panhandle",
    # Central Texas
    "Mclennan": "Central Texas",
    "Bell": "Central Texas",
    "Coryell": "Central Texas",
    "Falls": "Central Texas",
    "Limestone": "Central Texas",
    "Hill": "Central Texas",
    "Milam": "Central Texas",
    "Lampasas": "Central Texas",
    "Mills": "Central Texas",
    # Hill Country
    "Gillespie": "Hill Country",
    "Kerr": "Hill Country",
    "Blanco": "Hill Country",
    "Burnet": "Hill Country",
    "Llano": "Hill Country",
    "Mason": "Hill Country",
    "Kimble": "Hill Country",
    "Edwards": "Hill Country",
    "Real": "Hill Country",
    # Coastal Bend
    "Nueces": "Coastal Bend",
    "San Patricio": "Coastal Bend",
    "Aransas": "Coastal Bend",
    "Refugio": "Coastal Bend",
    "Kleberg": "Coastal Bend",
    "Brooks": "Coastal Bend",
    "Victoria": "Coastal Bend",
    "Calhoun": "Coastal Bend",
    "Jackson": "Coastal Bend",
    "Dewitt": "Coastal Bend",
    "Goliad": "Coastal Bend",
    "Bee": "Coastal Bend",
    "Live Oak": "Coastal Bend",
    # Brazos Valley
    "Brazos": "Brazos Valley",
    "Grimes": "Brazos Valley",
    "Burleson": "Brazos Valley",
    "Leon": "Brazos Valley",
    "Madison": "Brazos Valley",
    "Robertson": "Brazos Valley",
    "Washington": "Brazos Valley",
    # Big Bend
    "Brewster": "Big Bend",
    "Jeff Davis": "Big Bend",
    "Presidio": "Big Bend",
    "Pecos": "Big Bend",
    "Terrell": "Big Bend",
    "Culberson": "Big Bend",
    "Hudspeth": "Big Bend",
    # North Central
    "Taylor": "North Central",
    "Jones": "North Central",
    "Shackelford": "North Central",
    "Nolan": "North Central",
    "Fisher": "North Central",
    "Callahan": "North Central",
    "Eastland": "North Central",
    "Wichita": "North Central",
    "Archer": "North Central",
    "Clay": "North Central",
    "Young": "North Central",
    "Jack": "North Central",
    "Palo Pinto": "North Central",
    "Stephens": "North Central",
    "Baylor": "North Central",
    "Knox": "North Central",
    "Haskell": "North Central",
    "Throckmorton": "North Central",
    "Cottle": "North Central",
    "King": "North Central",
    "Stonewall": "North Central",
}
